server:
  port: 8099

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpatest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # System.out 으로 출력
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL 쿼리 로그
logging.level:
  org.hibernate.SQL: debug # Log 남김
# org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /hello/**
    - /api/**